# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

"""PEP 517 build backend for onnx

This is a thin wrapper over setuptools' PEP 517 build backend that
automatically adds ``cmake`` to build dependencies if there is no CMake
executable in PATH.  This approach ensures that the package uses system
CMake (that may contain downstream patches) when one is available,
and pulls in the CMake package from PyPI when it is not.
"""

from __future__ import annotations

import datetime
import os
import shutil
import subprocess
import textwrap

from setuptools.build_meta import (
    build_editable,
    build_wheel,
    get_requires_for_build_sdist,
    prepare_metadata_for_build_editable,
    prepare_metadata_for_build_wheel,
)
from setuptools.build_meta import (
    build_sdist as _build_sdist,
)
from setuptools.build_meta import (
    get_requires_for_build_editable as _get_requires_for_build_editable,
)
from setuptools.build_meta import (
    get_requires_for_build_wheel as _get_requires_for_build_wheel,
)

__all__ = [
    "build_editable",
    "build_sdist",
    "build_wheel",
    "get_requires_for_build_editable",
    "get_requires_for_build_sdist",
    "get_requires_for_build_wheel",
    "prepare_metadata_for_build_editable",
    "prepare_metadata_for_build_wheel",
]


def _get_cmake_dep() -> list[str]:
    if shutil.which("cmake3") or shutil.which("cmake"):
        return []
    return ["cmake>=3.18"]


def get_requires_for_build_editable(*args, **kwargs) -> list[str]:
    return _get_requires_for_build_editable(*args, **kwargs) + _get_cmake_dep()


def get_requires_for_build_wheel(*args, **kwargs) -> list[str]:
    return _get_requires_for_build_wheel(*args, **kwargs) + _get_cmake_dep()


def _get_version_info():
    """Compute version information without triggering setup."""
    top_dir = os.path.realpath(os.path.dirname(__file__))
    
    try:
        git_version = (
            subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=top_dir)
            .decode("ascii")
            .strip()
        )
    except (OSError, subprocess.CalledProcessError):
        git_version = ""

    with open(os.path.join(top_dir, "VERSION_NUMBER"), encoding="utf-8") as version_file:
        version = version_file.read().strip()
        
    onnx_preview_build = os.getenv("ONNX_PREVIEW_BUILD") == "1"
    if onnx_preview_build:
        todays_date = datetime.datetime.now(tz=datetime.timezone.utc).strftime("%Y%m%d")
        version += ".dev" + todays_date
        
    return {"version": version, "git_version": git_version}


def _create_version_file(directory: str):
    """Create onnx/version.py with the correct version."""
    version_info = _get_version_info()
    version_file_path = os.path.join(directory, "onnx", "version.py")
    os.makedirs(os.path.dirname(version_file_path), exist_ok=True)

    with open(version_file_path, "w", encoding="utf-8") as f:
        f.write(
            textwrap.dedent(
                f"""\
                # This file is generated by backend.py. DO NOT EDIT!

                version = "{version_info["version"]}"
                git_version = "{version_info["git_version"]}"
                """
            )
        )


def _ensure_version_file() -> None:
    """Ensure onnx/version.py is created with the correct version."""
    top_dir = os.path.realpath(os.path.dirname(__file__))
    _create_version_file(top_dir)


def build_sdist(sdist_directory: str, config_settings=None) -> str:
    """Override build_sdist to ensure version.py is created first."""
    _ensure_version_file()
    return _build_sdist(sdist_directory, config_settings=config_settings)
