{% set version = "1.0.1" %}

package:
  name: onnx
  version: {{ version }}

source:
  path: ..

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - protobuf
    - numpy
    - setuptools
    - python
    - pytest-runner
  run:
    - python
    - protobuf
    - numpy

about:
  home: https://github.com/onnx/onnx/
  license: BSD
  summary: Open Neural Network Exchange library

extra:
  recipe-maintainers:
    - ezyang
