# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container to /app
WORKDIR /app

# Copy the wheel file into the container
COPY ./dist/*.whl /app/

# docker build -t my_python_image -f Dockerfile.linux .
