# Copyright (c) ONNX Project Contributors

# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

import os
import sys
import tempfile
import unittest
from unittest.mock import patch

# Add the project root to the path so we can import backend
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import backend


class TestBackendBuild(unittest.TestCase):
    """Test the PEP 517 build backend functionality.
    
    Requirements:
    - Git repository access (for version info retrieval)
    - Write access to project directory (for version file creation)
    - VERSION_NUMBER file in project root
    """

    def test_get_version_info_regular(self):
        """Test _get_version_info returns correct version info for regular build."""
        version_info = backend._get_version_info()

        # Should have version and git_version keys
        self.assertIn("version", version_info)
        self.assertIn("git_version", version_info)

        # Version should start with content from VERSION_NUMBER
        with open(os.path.join(os.path.dirname(__file__), "..", "..", "VERSION_NUMBER"), encoding="utf-8") as f:
            expected_base_version = f.read().strip()
        self.assertTrue(version_info["version"].startswith(expected_base_version))

        # Git version should be a string (either actual hash or empty)
        self.assertIsInstance(version_info["git_version"], str)

    def test_get_version_info_preview(self):
        """Test _get_version_info returns correct version info for preview build."""
        with patch.dict(os.environ, {"ONNX_PREVIEW_BUILD": "1"}):
            version_info = backend._get_version_info()

            # Should have .dev suffix with date
            self.assertIn(".dev", version_info["version"])
            # Date should be in YYYYMMDD format
            date_part = version_info["version"].split(".dev")[1]
            self.assertEqual(len(date_part), 8)
            self.assertTrue(date_part.isdigit())

    def test_create_version_file(self):
        """Test _create_version_file creates correct version.py."""
        with tempfile.TemporaryDirectory() as temp_dir:
            # Create the version file
            backend._create_version_file(temp_dir)

            # Check the file was created
            version_file = os.path.join(temp_dir, "onnx", "version.py")
            self.assertTrue(os.path.exists(version_file))

            # Check the content
            with open(version_file, encoding="utf-8") as f:
                content = f.read()

            # Should contain the header comment
            self.assertIn("# This file is generated by backend.py. DO NOT EDIT!", content)
            # Should contain version and git_version assignments
            self.assertIn("version =", content)
            self.assertIn("git_version =", content)

    def test_ensure_version_file(self):
        """Test _ensure_version_file creates version.py in correct location."""
        # This should create onnx/version.py in the project root
        backend._ensure_version_file()

        version_file = os.path.join(os.path.dirname(__file__), "..", "version.py")
        self.assertTrue(os.path.exists(version_file))

        # Clean up
        if os.path.exists(version_file):
            os.remove(version_file)

    def test_backend_import_safe(self):
        """Test that importing backend doesn't execute setup.py."""
        # This test ensures that our fix prevents setup.py from being executed
        # during import. If setup.py were executed, it would likely cause issues
        # or at least be detectable.

        # Import should succeed without issues (backend is already imported above)
        # If we get here without errors, the import is safe
        self.assertTrue(True)


if __name__ == "__main__":
    unittest.main()