#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os

autogen_header = """\
//
// WARNING: This file is automatically generated!  Please edit onnx.proto.in.
//


"""

def main():
    onnx_proto_in = os.path.join(os.path.dirname(__file__), "onnx.proto.in")
    onnx_proto = os.path.join(os.path.dirname(__file__), "onnx.proto")
    with open(onnx_proto_in, 'r') as fin:
        # As of right now, it's a no-op.  Add whatever processing you want here
        with open(onnx_proto, 'w') as fout:
            fout.write(autogen_header)
            fout.write(fin.read())

if __name__ == '__main__':
    main()
