// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: onnx/onnx-operators-ml.proto

#include "onnx/onnx-operators-ml.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace onnx {

inline constexpr OperatorProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        op_type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        doc_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        since_version_{::int64_t{0}},
        status_{static_cast< ::onnx::OperatorStatus >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR OperatorProto::OperatorProto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct OperatorProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperatorProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperatorProtoDefaultTypeInternal() {}
  union {
    OperatorProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperatorProtoDefaultTypeInternal _OperatorProto_default_instance_;

inline constexpr OperatorSetProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        operator__{},
        functions_{},
        magic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ir_version_prerelease_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        domain_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        doc_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ir_build_metadata_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ir_version_{::int64_t{0}},
        opset_version_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR OperatorSetProto::OperatorSetProto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct OperatorSetProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperatorSetProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperatorSetProtoDefaultTypeInternal() {}
  union {
    OperatorSetProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperatorSetProtoDefaultTypeInternal _OperatorSetProto_default_instance_;
}  // namespace onnx
static ::_pb::Metadata file_level_metadata_onnx_2fonnx_2doperators_2dml_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_onnx_2fonnx_2doperators_2dml_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_onnx_2fonnx_2doperators_2dml_2eproto = nullptr;
const ::uint32_t TableStruct_onnx_2fonnx_2doperators_2dml_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorProto, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorProto, _impl_.op_type_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorProto, _impl_.since_version_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorProto, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorProto, _impl_.doc_string_),
    0,
    2,
    3,
    1,
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.magic_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.ir_version_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.ir_version_prerelease_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.ir_build_metadata_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.domain_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.opset_version_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.doc_string_),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.operator__),
    PROTOBUF_FIELD_OFFSET(::onnx::OperatorSetProto, _impl_.functions_),
    0,
    5,
    1,
    4,
    2,
    6,
    3,
    ~0u,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::onnx::OperatorProto)},
        {16, 33, -1, sizeof(::onnx::OperatorSetProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::onnx::_OperatorProto_default_instance_._instance,
    &::onnx::_OperatorSetProto_default_instance_._instance,
};
const char descriptor_table_protodef_onnx_2fonnx_2doperators_2dml_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\034onnx/onnx-operators-ml.proto\022\004onnx\032\022on"
    "nx/onnx-ml.proto\"q\n\rOperatorProto\022\017\n\007op_"
    "type\030\001 \001(\t\022\025\n\rsince_version\030\002 \001(\003\022$\n\006sta"
    "tus\030\003 \001(\0162\024.onnx.OperatorStatus\022\022\n\ndoc_s"
    "tring\030\n \001(\t\"\371\001\n\020OperatorSetProto\022\r\n\005magi"
    "c\030\001 \001(\t\022\022\n\nir_version\030\002 \001(\003\022\035\n\025ir_versio"
    "n_prerelease\030\003 \001(\t\022\031\n\021ir_build_metadata\030"
    "\007 \001(\t\022\016\n\006domain\030\004 \001(\t\022\025\n\ropset_version\030\005"
    " \001(\003\022\022\n\ndoc_string\030\006 \001(\t\022%\n\010operator\030\010 \003"
    "(\0132\023.onnx.OperatorProto\022&\n\tfunctions\030\t \003"
    "(\0132\023.onnx.FunctionProto"
};
static const ::_pbi::DescriptorTable* const descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_deps[1] =
    {
        &::descriptor_table_onnx_2fonnx_2dml_2eproto,
};
static ::absl::once_flag descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto = {
    false,
    false,
    423,
    descriptor_table_protodef_onnx_2fonnx_2doperators_2dml_2eproto,
    "onnx/onnx-operators-ml.proto",
    &descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_once,
    descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_onnx_2fonnx_2doperators_2dml_2eproto::offsets,
    file_level_metadata_onnx_2fonnx_2doperators_2dml_2eproto,
    file_level_enum_descriptors_onnx_2fonnx_2doperators_2dml_2eproto,
    file_level_service_descriptors_onnx_2fonnx_2doperators_2dml_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_getter() {
  return &descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_onnx_2fonnx_2doperators_2dml_2eproto(&descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto);
namespace onnx {
// ===================================================================

class OperatorProto::_Internal {
 public:
  using HasBits = decltype(std::declval<OperatorProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_._has_bits_);
  static void set_has_op_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_since_version(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_status(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_doc_string(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

OperatorProto::OperatorProto(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:onnx.OperatorProto)
}
inline PROTOBUF_NDEBUG_INLINE OperatorProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        op_type_(arena, from.op_type_),
        doc_string_(arena, from.doc_string_) {}

OperatorProto::OperatorProto(
    ::google::protobuf::Arena* arena,
    const OperatorProto& from)
    : ::google::protobuf::Message(arena) {
  OperatorProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, since_version_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, since_version_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, since_version_) +
               sizeof(Impl_::status_));

  // @@protoc_insertion_point(copy_constructor:onnx.OperatorProto)
}
inline PROTOBUF_NDEBUG_INLINE OperatorProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        op_type_(arena),
        doc_string_(arena) {}

inline void OperatorProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, since_version_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, since_version_) +
               sizeof(Impl_::status_));
}
OperatorProto::~OperatorProto() {
  // @@protoc_insertion_point(destructor:onnx.OperatorProto)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void OperatorProto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.op_type_.Destroy();
  _impl_.doc_string_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void OperatorProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.OperatorProto)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.op_type_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.doc_string_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.since_version_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.status_) -
        reinterpret_cast<char*>(&_impl_.since_version_)) + sizeof(_impl_.status_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* OperatorProto::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 44, 2> OperatorProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_._has_bits_),
    0, // no _extensions_
    10, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966776,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_OperatorProto_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string op_type = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.op_type_)}},
    // optional int64 since_version = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(OperatorProto, _impl_.since_version_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.since_version_)}},
    // optional .onnx.OperatorStatus status = 3;
    {::_pbi::TcParser::FastEr0S1,
     {24, 3, 1, PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string op_type = 1;
    {PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.op_type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int64 since_version = 2;
    {PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.since_version_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .onnx.OperatorStatus status = 3;
    {PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.status_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional string doc_string = 10;
    {PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.doc_string_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }}, {{
    {0, 2},
  }}, {{
    "\22\7\0\0\12\0\0\0"
    "onnx.OperatorProto"
    "op_type"
    "doc_string"
  }},
};

::uint8_t* OperatorProto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:onnx.OperatorProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string op_type = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_op_type();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "onnx.OperatorProto.op_type");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int64 since_version = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_since_version(), target);
  }

  // optional .onnx.OperatorStatus status = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this->_internal_status(), target);
  }

  // optional string doc_string = 10;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_doc_string();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "onnx.OperatorProto.doc_string");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onnx.OperatorProto)
  return target;
}

::size_t OperatorProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.OperatorProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string op_type = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_op_type());
    }

    // optional string doc_string = 10;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_doc_string());
    }

    // optional int64 since_version = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_since_version());
    }

    // optional .onnx.OperatorStatus status = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData OperatorProto::_class_data_ = {
    OperatorProto::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* OperatorProto::GetClassData() const {
  return &_class_data_;
}

void OperatorProto::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<OperatorProto*>(&to_msg);
  auto& from = static_cast<const OperatorProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:onnx.OperatorProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_op_type(from._internal_op_type());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_doc_string(from._internal_doc_string());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.since_version_ = from._impl_.since_version_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.status_ = from._impl_.status_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OperatorProto::CopyFrom(const OperatorProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.OperatorProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool OperatorProto::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* OperatorProto::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void OperatorProto::InternalSwap(OperatorProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.op_type_, &other->_impl_.op_type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.doc_string_, &other->_impl_.doc_string_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.status_)
      + sizeof(OperatorProto::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(OperatorProto, _impl_.since_version_)>(
          reinterpret_cast<char*>(&_impl_.since_version_),
          reinterpret_cast<char*>(&other->_impl_.since_version_));
}

::google::protobuf::Metadata OperatorProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_getter, &descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_once,
      file_level_metadata_onnx_2fonnx_2doperators_2dml_2eproto[0]);
}
// ===================================================================

class OperatorSetProto::_Internal {
 public:
  using HasBits = decltype(std::declval<OperatorSetProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_._has_bits_);
  static void set_has_magic(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_ir_version(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_ir_version_prerelease(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_ir_build_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_domain(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_opset_version(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_doc_string(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

void OperatorSetProto::clear_functions() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.functions_.Clear();
}
OperatorSetProto::OperatorSetProto(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:onnx.OperatorSetProto)
}
inline PROTOBUF_NDEBUG_INLINE OperatorSetProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        operator__{visibility, arena, from.operator__},
        functions_{visibility, arena, from.functions_},
        magic_(arena, from.magic_),
        ir_version_prerelease_(arena, from.ir_version_prerelease_),
        domain_(arena, from.domain_),
        doc_string_(arena, from.doc_string_),
        ir_build_metadata_(arena, from.ir_build_metadata_) {}

OperatorSetProto::OperatorSetProto(
    ::google::protobuf::Arena* arena,
    const OperatorSetProto& from)
    : ::google::protobuf::Message(arena) {
  OperatorSetProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ir_version_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, ir_version_),
           offsetof(Impl_, opset_version_) -
               offsetof(Impl_, ir_version_) +
               sizeof(Impl_::opset_version_));

  // @@protoc_insertion_point(copy_constructor:onnx.OperatorSetProto)
}
inline PROTOBUF_NDEBUG_INLINE OperatorSetProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        operator__{visibility, arena},
        functions_{visibility, arena},
        magic_(arena),
        ir_version_prerelease_(arena),
        domain_(arena),
        doc_string_(arena),
        ir_build_metadata_(arena) {}

inline void OperatorSetProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ir_version_),
           0,
           offsetof(Impl_, opset_version_) -
               offsetof(Impl_, ir_version_) +
               sizeof(Impl_::opset_version_));
}
OperatorSetProto::~OperatorSetProto() {
  // @@protoc_insertion_point(destructor:onnx.OperatorSetProto)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void OperatorSetProto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.magic_.Destroy();
  _impl_.ir_version_prerelease_.Destroy();
  _impl_.domain_.Destroy();
  _impl_.doc_string_.Destroy();
  _impl_.ir_build_metadata_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void OperatorSetProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.OperatorSetProto)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.operator__.Clear();
  _impl_.functions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.magic_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.ir_version_prerelease_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.domain_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.doc_string_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.ir_build_metadata_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000060u) {
    ::memset(&_impl_.ir_version_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.opset_version_) -
        reinterpret_cast<char*>(&_impl_.ir_version_)) + sizeof(_impl_.opset_version_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* OperatorSetProto::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 2, 97, 2> OperatorSetProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_OperatorSetProto_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string magic = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.magic_)}},
    // optional int64 ir_version = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(OperatorSetProto, _impl_.ir_version_), 5>(),
     {16, 5, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.ir_version_)}},
    // optional string ir_version_prerelease = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.ir_version_prerelease_)}},
    // optional string domain = 4;
    {::_pbi::TcParser::FastSS1,
     {34, 2, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.domain_)}},
    // optional int64 opset_version = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(OperatorSetProto, _impl_.opset_version_), 6>(),
     {40, 6, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.opset_version_)}},
    // optional string doc_string = 6;
    {::_pbi::TcParser::FastSS1,
     {50, 3, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.doc_string_)}},
    // optional string ir_build_metadata = 7;
    {::_pbi::TcParser::FastSS1,
     {58, 4, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.ir_build_metadata_)}},
    // repeated .onnx.OperatorProto operator = 8;
    {::_pbi::TcParser::FastMtR1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.operator__)}},
    // repeated .onnx.FunctionProto functions = 9;
    {::_pbi::TcParser::FastMtR1,
     {74, 63, 1, PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.functions_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string magic = 1;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.magic_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int64 ir_version = 2;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.ir_version_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional string ir_version_prerelease = 3;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.ir_version_prerelease_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string domain = 4;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.domain_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int64 opset_version = 5;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.opset_version_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional string doc_string = 6;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.doc_string_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string ir_build_metadata = 7;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.ir_build_metadata_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated .onnx.OperatorProto operator = 8;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.operator__), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .onnx.FunctionProto functions = 9;
    {PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.functions_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::onnx::OperatorProto>()},
    {::_pbi::TcParser::GetTable<::onnx::FunctionProto>()},
  }}, {{
    "\25\5\0\25\6\0\12\21\0\0\0\0\0\0\0\0"
    "onnx.OperatorSetProto"
    "magic"
    "ir_version_prerelease"
    "domain"
    "doc_string"
    "ir_build_metadata"
  }},
};

::uint8_t* OperatorSetProto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:onnx.OperatorSetProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string magic = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_magic();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "onnx.OperatorSetProto.magic");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int64 ir_version = 2;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_ir_version(), target);
  }

  // optional string ir_version_prerelease = 3;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_ir_version_prerelease();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "onnx.OperatorSetProto.ir_version_prerelease");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string domain = 4;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_domain();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "onnx.OperatorSetProto.domain");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional int64 opset_version = 5;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<5>(
            stream, this->_internal_opset_version(), target);
  }

  // optional string doc_string = 6;
  if (cached_has_bits & 0x00000008u) {
    const std::string& _s = this->_internal_doc_string();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "onnx.OperatorSetProto.doc_string");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // optional string ir_build_metadata = 7;
  if (cached_has_bits & 0x00000010u) {
    const std::string& _s = this->_internal_ir_build_metadata();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "onnx.OperatorSetProto.ir_build_metadata");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // repeated .onnx.OperatorProto operator = 8;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_operator__size()); i < n; i++) {
    const auto& repfield = this->_internal_operator_().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(8, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .onnx.FunctionProto functions = 9;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_functions_size()); i < n; i++) {
    const auto& repfield = this->_internal_functions().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(9, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onnx.OperatorSetProto)
  return target;
}

::size_t OperatorSetProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.OperatorSetProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .onnx.OperatorProto operator = 8;
  total_size += 1UL * this->_internal_operator__size();
  for (const auto& msg : this->_internal_operator_()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .onnx.FunctionProto functions = 9;
  total_size += 1UL * this->_internal_functions_size();
  for (const auto& msg : this->_internal_functions()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional string magic = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_magic());
    }

    // optional string ir_version_prerelease = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_ir_version_prerelease());
    }

    // optional string domain = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_domain());
    }

    // optional string doc_string = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_doc_string());
    }

    // optional string ir_build_metadata = 7;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_ir_build_metadata());
    }

    // optional int64 ir_version = 2;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_ir_version());
    }

    // optional int64 opset_version = 5;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_opset_version());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData OperatorSetProto::_class_data_ = {
    OperatorSetProto::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* OperatorSetProto::GetClassData() const {
  return &_class_data_;
}

void OperatorSetProto::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<OperatorSetProto*>(&to_msg);
  auto& from = static_cast<const OperatorSetProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:onnx.OperatorSetProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_operator_()->MergeFrom(
      from._internal_operator_());
  _this->_internal_mutable_functions()->MergeFrom(
      from._internal_functions());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_magic(from._internal_magic());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_ir_version_prerelease(from._internal_ir_version_prerelease());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_domain(from._internal_domain());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_doc_string(from._internal_doc_string());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_ir_build_metadata(from._internal_ir_build_metadata());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.ir_version_ = from._impl_.ir_version_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.opset_version_ = from._impl_.opset_version_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OperatorSetProto::CopyFrom(const OperatorSetProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.OperatorSetProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool OperatorSetProto::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* OperatorSetProto::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void OperatorSetProto::InternalSwap(OperatorSetProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.operator__.InternalSwap(&other->_impl_.operator__);
  _impl_.functions_.InternalSwap(&other->_impl_.functions_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.magic_, &other->_impl_.magic_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ir_version_prerelease_, &other->_impl_.ir_version_prerelease_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.domain_, &other->_impl_.domain_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.doc_string_, &other->_impl_.doc_string_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ir_build_metadata_, &other->_impl_.ir_build_metadata_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.opset_version_)
      + sizeof(OperatorSetProto::_impl_.opset_version_)
      - PROTOBUF_FIELD_OFFSET(OperatorSetProto, _impl_.ir_version_)>(
          reinterpret_cast<char*>(&_impl_.ir_version_),
          reinterpret_cast<char*>(&other->_impl_.ir_version_));
}

::google::protobuf::Metadata OperatorSetProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_getter, &descriptor_table_onnx_2fonnx_2doperators_2dml_2eproto_once,
      file_level_metadata_onnx_2fonnx_2doperators_2dml_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace onnx
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
