# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Test (pip install -e .)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:  # set top-level default permissions as security best practice
  contents: read

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ['3.9', '3.13']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies, build ONNX
        run: |
          python -m pip install -q --upgrade pip
          python -m pip install -r requirements-release.txt
          git submodule update --init --recursive

          source workflow_scripts/protobuf/build_protobuf_unix.sh 3
                  
          pip install -e .
   
