# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Pixi CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit-hooks:
    name: Install and lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: ${{ matrix.environment }} reuse
      - name: Install repository
        run: pixi run install
      - name: Lint
        run: pixi run lint --show-diff-on-failure

  install-and-test:
    name: Install and test (${{ matrix.os }}, ${{ matrix.environment }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      issues: write  # Needed to create an issue on failure

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-latest
          - macos-latest
          - windows-latest
        environment:
          - default
          - oldies
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: ${{ matrix.environment }}
      - name: Install repository
        run: pixi run -e ${{ matrix.environment }} install
      - name: pip check installation
        run: pixi run -e ${{ matrix.environment }} pip check
      - name: gtests
        run: pixi run -e ${{ matrix.environment }} gtest
      - name: pytest
        run: pixi run -e ${{ matrix.environment }} pytest
      - name: Issue on failure
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          script: |
            github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              labels: "[bot] pixi CI"
            }).then((issues) => {
              if (issues.data.length === 0){
                github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: "Scheduled pixi CI failed",
                  body: "The scheduled pixi-based CI failed. See https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}} for details.",
                  assignees: ["cbourjau"],
                  labels: ["[bot] pixi CI"]
                })
              }
            });
