# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: PR Checks Post

on:
  workflow_run:
    workflows: ["PR Checks"]
    types:
      - completed

permissions:
  contents: read

jobs:
  suggest-changes:
    name: Suggest fixes
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        continue-on-error: true
        with:
          name: pr-artifacts
          path: /tmp/pr_artifacts/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR number
        if: steps.download.outcome == 'success'
        id: pr
        run: echo "number=$(cat /tmp/pr_artifacts/pr_number)" >> "$GITHUB_OUTPUT"
      - name: Checkout PR
        if: steps.download.outcome == 'success'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: refs/pull/${{ steps.pr.outputs.number }}/head
          persist-credentials: false
      - name: Install reviewdog
        if: steps.download.outcome == 'success'
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/9b54cccfb4bf2509aef8a3e26899412348b62ce9/install.sh \
            | sh -s -- -b /usr/local/bin v0.21.0
      - name: Suggest changes
        if: steps.download.outcome == 'success'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_PULL_REQUEST: ${{ steps.pr.outputs.number }}
          CI_COMMIT: ${{ github.event.workflow_run.head_sha }}
          CI_REPO_OWNER: ${{ github.repository_owner }}
          CI_REPO_NAME: ${{ github.event.repository.name }}
        run: reviewdog -f=diff -reporter=github-pr-review < /tmp/pr_artifacts/lintrunner.diff
