# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Test_sdist_weekly

on:  # Specifies the event triggering the workflow
  workflow_call:  # Indicates that this is a reusable workflow
    inputs:
      os:
        required: true
        type: string

env:
  MACOSX_DEPLOYMENT_TARGET: "12.0"

permissions:
  contents: read

jobs:

  test_sdist_weekly:

    runs-on: ${{ (matrix.target-architecture == 'x86_64') && 'macos-15' || 'macos-14' }}
    strategy:
      matrix:
        python-version: ['3.10']
        target-architecture: ['arm64']

    steps:

        - name: Test weekly source distribution from PyPI
          if: github.event_name == 'schedule' && matrix.python-version == '3.10' && matrix.target-architecture == 'arm64'
          run: |
            python -m pip uninstall -y onnx-weekly
            python -m pip install setuptools
            python -m pip install --use-deprecated=legacy-resolver --no-binary onnx-weekly onnx-weekly
            pytest
